name: UI demo deploy to pages

on:
  push:
    branches:
    - '**'

jobs:
  # GitHub Pages artifact prepare
  upload-pages-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Rename index file
      run: mv src/ui-demo.html src/index.html
    - name: Upload artifact for pages deploy
      uses: actions/upload-pages-artifact@v4
      with:
        path: src


  # GitHub Pages deployment
  deploy-pages:
    # Deployment for only main branch, build steps are for all
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    needs: [upload-pages-artifact]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
    - name: Deploy pages
      id: deploy-pages
      uses: actions/deploy-pages@v4
